### ISSUE TITLE
Remove smoothing of graphs

### ISSUE THREAD

**Issue by armenzg** [mozilla/bugzilla-dashboard#62]
![image](https://user-images.githubusercontent.com/44410/55826518-30d0c400-5ad6-11e9-8967-12c489b53988.png)

**Comment by armenzg** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/44410/55900272-ce8ac880-5b94-11e9-84e2-46736bfd9ded.png)

**Comment by sylvestre** [comment]
Would it be possible to still have a line but without the smoothy?
